# Generated by Django 4.1 on 2025-07-05 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="任务ID"
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("qiime2", "QIIME2分析"),
                            ("diversity", "多样性分析"),
                            ("taxonomy", "分类学分析"),
                            ("functional", "功能分析"),
                        ],
                        max_length=20,
                        verbose_name="分析类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(blank=True, default=dict, verbose_name="分析参数"),
                ),
                (
                    "result_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="结果路径"
                    ),
                ),
                (
                    "log_file",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="日志文件"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
            ],
            options={
                "verbose_name": "分析任务",
                "verbose_name_plural": "分析任务",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_name",
                    models.CharField(max_length=200, verbose_name="样本名称"),
                ),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("fastq", "FASTQ文件"),
                            ("fasta", "FASTA文件"),
                            ("biom", "BIOM文件"),
                            ("other", "其他格式"),
                        ],
                        max_length=20,
                        verbose_name="样本类型",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(upload_to="samples/", verbose_name="文件路径"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "upload_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="上传时间"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="样本描述"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "样本",
                "verbose_name_plural": "样本",
                "ordering": ["-upload_time"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="电话"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="机构"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="个人简介"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="zh-cn", max_length=10, verbose_name="首选语言"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(default=True, verbose_name="邮件通知"),
                ),
                (
                    "total_samples",
                    models.IntegerField(default=0, verbose_name="总样本数"),
                ),
                (
                    "total_analyses",
                    models.IntegerField(default=0, verbose_name="总分析数"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户配置",
                "verbose_name_plural": "用户配置",
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("upload", "上传文件"),
                            ("analysis", "开始分析"),
                            ("download", "下载结果"),
                            ("view_result", "查看结果"),
                            ("delete", "删除数据"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="操作描述"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("user_agent", models.TextField(verbose_name="用户代理")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间戳"
                    ),
                ),
                (
                    "related_sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bioanalysis.sample",
                        verbose_name="相关样本",
                    ),
                ),
                (
                    "related_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bioanalysis.analysistask",
                        verbose_name="相关任务",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户操作日志",
                "verbose_name_plural": "用户操作日志",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("analysis", "分析配置"),
                            ("storage", "存储配置"),
                            ("notification", "通知配置"),
                            ("security", "安全配置"),
                        ],
                        max_length=20,
                        verbose_name="配置类型",
                    ),
                ),
                ("config_key", models.CharField(max_length=100, verbose_name="配置键")),
                ("config_value", models.TextField(verbose_name="配置值")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "unique_together": {("config_type", "config_key")},
            },
        ),
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("autism_risk", "自闭症风险预测"),
                            ("disease_risk", "疾病风险预测"),
                            ("health_index", "健康指数评估"),
                        ],
                        max_length=20,
                        verbose_name="预测类型",
                    ),
                ),
                ("prediction_score", models.FloatField(verbose_name="预测得分")),
                ("confidence", models.FloatField(verbose_name="置信度")),
                (
                    "risk_level",
                    models.CharField(max_length=20, verbose_name="风险等级"),
                ),
                (
                    "detailed_results",
                    models.JSONField(default=dict, verbose_name="详细结果"),
                ),
                (
                    "feature_importance",
                    models.JSONField(default=dict, verbose_name="特征重要性"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "analysis_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bioanalysis.analysistask",
                        verbose_name="分析任务",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "预测结果",
                "verbose_name_plural": "预测结果",
                "ordering": ["-created_time"],
            },
        ),
        migrations.AddField(
            model_name="analysistask",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bioanalysis.sample",
                verbose_name="样本",
            ),
        ),
        migrations.AddField(
            model_name="analysistask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
