# Generated by Django 4.1 on 2025-07-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bioanalysis", "0002_analysistask_result_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysistask",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="analysistask",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="user",
        ),
        migrations.DeleteModel(
            name="SystemConfig",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="predictionresult",
            name="analysis_task",
        ),
        migrations.RemoveField(
            model_name="predictionresult",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="predictionresult",
            name="detailed_results",
        ),
        migrations.RemoveField(
            model_name="predictionresult",
            name="feature_importance",
        ),
        migrations.RemoveField(
            model_name="predictionresult",
            name="prediction_score",
        ),
        migrations.RemoveField(
            model_name="predictionresult",
            name="risk_level",
        ),
        migrations.RemoveField(
            model_name="useractivitylog",
            name="related_sample",
        ),
        migrations.RemoveField(
            model_name="useractivitylog",
            name="related_task",
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="confidence_score",
            field=models.FloatField(default=0.0, verbose_name="置信度分数"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="input_data",
            field=models.TextField(default="", verbose_name="输入数据"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="model_version",
            field=models.CharField(
                default="v1.0", max_length=50, verbose_name="模型版本"
            ),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="prediction_result",
            field=models.TextField(default="{}", verbose_name="预测结果"),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="sample_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="样本ID"),
        ),
        migrations.AlterField(
            model_name="predictionresult",
            name="prediction_type",
            field=models.CharField(
                choices=[("autism_risk", "自闭症风险预测")],
                default="autism_risk",
                max_length=20,
                verbose_name="预测类型",
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("login", "登录"),
                    ("logout", "登出"),
                    ("upload", "上传文件"),
                    ("analysis", "开始分析"),
                    ("prediction_start", "开始预测"),
                    ("view_result", "查看结果"),
                    ("error", "错误"),
                    ("delete", "删除数据"),
                ],
                max_length=20,
                verbose_name="操作类型",
            ),
        ),
        migrations.AddIndex(
            model_name="predictionresult",
            index=models.Index(
                fields=["user", "sample_id"], name="bioanalysis_user_id_4d030f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionresult",
            index=models.Index(
                fields=["created_time"], name="bioanalysis_created_a6071f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["user", "action_type"], name="bioanalysis_user_id_4821a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["timestamp"], name="bioanalysis_timesta_3bfca9_idx"
            ),
        ),
        migrations.DeleteModel(
            name="AnalysisTask",
        ),
        migrations.DeleteModel(
            name="Sample",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
