# Generated by Django 5.2.3 on 2025-08-11 05:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bioanalysis",
            "0003_remove_analysistask_sample_remove_analysistask_user_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="操作时间"
            ),
        ),
        migrations.CreateModel(
            name="DiseasePredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_name", models.CharField(max_length=255)),
                (
                    "prediction_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("prediction_results", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-prediction_time"],
            },
        ),
    ]
